export const NOTIFICATIONS_DI_TOKENS = {
  REPOSITORIES: {
    EMAIL_TEMPLATES: Symbol.for('NOTIFICATIONS_EMAIL_TEMPLATES_REPOSITORY'),
  },
  SERVICES: {
    TEMPLATE_RENDERER: Symbol.for('NOTIFICATIONS_TEMPLATE_RENDERER_SERVICE'),
    EMAIL_SENDER: Symbol.for('NOTIFICATIONS_EMAIL_SENDER_SERVICE'),
    USER_RESOLVER: Symbol.for('NOTIFICATIONS_USER_RESOLVER_SERVICE'),
    EMAIL_TEMPLATE_CACHE: Symbol.for('NOTIFICATIONS_EMAIL_TEMPLATE_CACHE_SERVICE'),
  },
  CONFIGS: {
    NOTIFICATIONS: Symbol.for('NOTIFICATIONS_CONFIG'),
  },
  USE_CASES: {
    CREATE_EMAIL_TEMPLATE: Symbol.for('NOTIFICATIONS_CREATE_EMAIL_TEMPLATE_USE_CASE'),
    GET_EMAIL_TEMPLATE: Symbol.for('NOTIFICATIONS_GET_EMAIL_TEMPLATE_USE_CASE'),
    UPDATE_EMAIL_TEMPLATE: Symbol.for('NOTIFICATIONS_UPDATE_EMAIL_TEMPLATE_USE_CASE'),
    DELETE_EMAIL_TEMPLATE: Symbol.for('NOTIFICATIONS_DELETE_EMAIL_TEMPLATE_USE_CASE'),
    LIST_EMAIL_TEMPLATES: Symbol.for('NOTIFICATIONS_LIST_EMAIL_TEMPLATES_USE_CASE'),
    PROCESS_EVENT_NOTIFICATION: Symbol.for('NOTIFICATIONS_PROCESS_EVENT_NOTIFICATION_USE_CASE'),
  },
} as const;
