export const APPLICATION_DI_TOKENS = {
  REPOSITORIES: {
    APPLICATION: Symbol.for('APPLICATION_REPOSITORY'),
  },
  PORTS: {
    EMAIL_SENDER: Symbol.for('APPLICATION_EMAIL_SENDER'),
    AI_SUMMARIZER: Symbol.for('APPLICATION_AI_SUMMARIZER'),
    PDF_PARSER: Symbol.for('APPLICATION_PDF_PARSER'),
    PUBLIC_URL: Symbol.for('APPLICATION_PUBLIC_URL'),
  },
  USE_CASES: {
    CREATE: Symbol.for('CREATE_APPLICATION_USE_CASE'),
    UPDATE: Symbol.for('UPDATE_APPLICATION_USE_CASE'),
    SEND: Symbol.for('SEND_APPLICATION_USE_CASE'),
    SUBMIT: Symbol.for('SUBMIT_APPLICATION_USE_CASE'),
    DECIDE: Symbol.for('DECIDE_APPLICATION_USE_CASE'),
    GET: Symbol.for('GET_APPLICATION_USE_CASE'),
    GET_BY_TOKEN: Symbol.for('GET_APPLICATION_BY_TOKEN_USE_CASE'),
    LIST: Symbol.for('LIST_APPLICATIONS_USE_CASE'),
    DELETE: Symbol.for('DELETE_APPLICATION_USE_CASE'),
    AI_SUMMARY: Symbol.for('GENERATE_AI_SUMMARY_USE_CASE'),
    PARSE_PDF: Symbol.for('PARSE_APPLICATION_PDF_USE_CASE'),
  },
} as const;
